# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

formatting:
  Indentation:
    active: true
  NoWildcardImports:
    active: false
complexity:
  TooManyFunctions:
    ignorePrivate: true
style:
  MagicNumber:
    active: false
  WildcardImport:
    excludeImports: ['java.util.*', 'kotlinx.coroutines.*']
